language: node_js
node_js:
  - "8.11.4"

cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: app-honduras.surge.sh
  project: ./build/
on:
  branch: master

